### ISSUE TITLE
DHC: Random bullet point in timeline

### ISSUE THREAD

**Issue by nkferraiolo** [clirdlf/clir_theme#162]
There's a random burgundy bullet point in the key dates timeline. Can we remove it?

**Comment by waynegraham** [comment]
It's not random; just didn't move with the rest when the box and line were resized.

**Comment by waynegraham** [comment]
This is working locally in https://github.com/clirdlf/clir_theme/commit/676dce7e50c6ed3349d8358c385cbb08e252d8c7#diff-3c163b1652a25adf6132ba751f71ae2e, but style for `.magee-timeline:before` isn't being respected. I suspect there's something going on with browser caching, but need to investigate further.

**Comment by waynegraham** [comment]
I couldn't get the correct CSS precedence order on the server for some reason and the parent theme was overriding the child theme setting. In order to move on, I changed this in the parent theme, but if the parent theme is updated at any point, this will creep back up again. 

`css/shortcode.css`

Line 1838, set `top: 64px`
